backend:
  name: git-gateway
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor
# publish_mode: editorial_workflow
show_preview_links: false
media_folder: "packages/demo/docs/assets" # Media files will be stored in the repo under static/images/uploads
public_folder: "/assets" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "event" # Used in routes, e.g., /admin/collections/blog
    label: "Events" # Used in the UI
    folder: "packages/demo/docs/events" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    format: 'yaml-frontmatter'
    editor: 
      preview: false 
    sort: "date:desc" # Default is title:asc
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Event Date", name: "eventdate", widget: "datetime", format: "dddd MMMM Do, YYYY"}
      - {label: "Publish Date", name: "publishdate", widget: "datetime", format: "dddd MMMM Do, YYYY"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "network" # Used in routes, e.g., /admin/collections/blog
    label: "Network" # Used in the UI
    folder: "packages/demo/docs/network" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    format: 'yaml-frontmatter'
    editor: 
      preview: false 
    sort: "title:asc" # Default is title:asc
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "dddd MMMM Do, YYYY"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "join" # Used in routes, e.g., /admin/collections/blog
    label: "Join" # Used in the UI
    folder: "packages/demo/docs/join" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    format: 'yaml-frontmatter'
    editor: 
      preview: false 
    sort: "title:asc" # Default is title:asc
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "dddd MMMM Do, YYYY"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "allies" # Used in routes, e.g., /admin/collections/blog
    label: "Allies" # Used in the UI
    folder: "packages/demo/docs/allies" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    format: 'yaml-frontmatter'
    editor: 
      preview: false 
    sort: "title:asc" # Default is title:asc
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "dddd MMMM Do, YYYY"}
      - {label: "Body", name: "body", widget: "markdown"}